Вариант с knn на чеках и NN на только характеристиках

In [1]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('corr_sales_biv_preprocess_full.csv', encoding='cp1251', sep=',', low_memory=False)
pd.set_option('display.max_columns', None)
df.head(5)
df.drop('Unnamed: 0', axis= 1 , inplace= True )

In [3]:
#df.info(verbose = True, show_counts = True)

In [4]:
df2_full = df.iloc[:,[1,16,27,28,32,33,34,35,40,43,44]]
df2_data = df.iloc[:,[16,27,28,32,33,34,35,40,43,44]]
df2_data.head(5)

r_value  height  inner_tent_height  depth  rope_diameter  sl_bag_length  \
0      0.0     0.0                0.0    0.0            0.0            0.0   
1      0.0     0.0                0.0    0.0            0.0            0.0   
2      0.0     0.0                0.0    0.0            0.0            0.0   
3      0.0     0.0                0.0    0.0            0.0            0.0   
4      0.0     0.0                0.0    0.0            0.0            0.0   

   sl_bag_height  main_axe_load  volume  real_weight  
0            0.0            0.0     0.0        0.709  
1            0.0            0.0     0.0        0.709  
2            0.0            0.0     0.0        0.709  
3            0.0            0.0     0.0        0.709  
4            0.0            0.0     0.0        0.709

In [5]:
df3 = df.iloc[:,55:483]
df4 = df.iloc[:,491:529]
df_fin = df.iloc[:,487:489]
#df3.head(5)

In [6]:
# Вариант с данными в нейронку только по характеристикам товара и чеки отдельно только в KNN
df_toteach = pd.concat([df2_data,df3], axis=1)
df_tocheck = pd.concat([df2_full,df3], axis=1)

df_toteach = pd.concat([df_toteach,df4], axis=1)
df_tocheck = pd.concat([df_tocheck,df4], axis=1)

df_toteach = pd.concat([df_toteach,df_fin], axis=1)
df_tocheck = pd.concat([df_tocheck,df_fin], axis=1)
#df_toteach.info(verbose = True, show_counts = True)

In [7]:
df_nano_full0 = df.iloc[:,[1,12,13, 14]]
df_nano_data0 = df.iloc[:,[12,13, 14]]
df_nano_full0.head(5)

name  discount_sum  total_sum  prod_unit_price
0  Тент ENO ProFly XL Sil Lichen        2580.0    10320.0          12900.0
1  Тент ENO ProFly XL Sil Lichen        2580.0    10320.0          12900.0
2  Тент ENO ProFly XL Sil Lichen        2580.0    10320.0          12900.0
3  Тент ENO ProFly XL Sil Lichen        6120.0     6780.0          12900.0
4  Тент ENO ProFly XL Sil Lichen        1935.0    10965.0          12900.0

In [8]:
df_nano2 = df.iloc[:,483:487]
df_nano3 = df.iloc[:,489:491]
df_nano3.head(5)

customer_keys_le  uid_docs_le
0              1927         4248
1               880         2501
2              1273         4021
3              2581         5537
4              2056         6523

In [9]:
df_nano_teach = pd.concat([df_nano_data0,df_nano2], axis=1)
df_nano_teach =  pd.concat([df_nano_teach,df_nano3], axis=1)
#df_nano_teach.head(5)
df_nano_tocheck = pd.concat([df_nano_full0,df_nano2], axis=1)
df_nano_tocheck = pd.concat([df_nano_tocheck,df_nano3], axis=1)
df_nano_tocheck.head(5)

name  discount_sum  total_sum  prod_unit_price  \
0  Тент ENO ProFly XL Sil Lichen        2580.0    10320.0          12900.0   
1  Тент ENO ProFly XL Sil Lichen        2580.0    10320.0          12900.0   
2  Тент ENO ProFly XL Sil Lichen        2580.0    10320.0          12900.0   
3  Тент ENO ProFly XL Sil Lichen        6120.0     6780.0          12900.0   
4  Тент ENO ProFly XL Sil Lichen        1935.0    10965.0          12900.0   

   quarter_1  quarter_2  quarter_3  quarter_4  customer_keys_le  uid_docs_le  
0          0          1          0          0              1927         4248  
1          0          1          0          0               880         2501  
2          0          1          0          0              1273         4021  
3          0          0          1          0              2581         5537  
4          0          0          1          0              2056         6523

In [10]:
#df_toteach.info(verbose = True, show_counts = True)

In [11]:
X = df_nano_teach.iloc[:,:-1]
y = df_nano_teach.iloc[:,-1:].to_numpy().ravel()

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 0)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
clf = KNeighborsClassifier(n_neighbors = 600)

In [14]:
clf.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=600)

In [15]:
print("Прогноз на тестовом наборе: {}".format(clf.predict(X_test)))

Прогноз на тестовом наборе: [ 291 4113  687 ... 4113 5488 2288]


In [16]:
print ("Правильность на тестовом наборе: {}".format(clf.score(X_test, y_test)))

Правильность на тестовом наборе: 0.011710581346716854


In [17]:
uid_dc_labels = clf.predict(X)

In [18]:
df_nano_tocheck['clusters'] = uid_dc_labels

#df_nano_tocheck.head(5)

In [19]:
df_inside_cluster = df_nano_tocheck.loc[(df_nano_tocheck['clusters'] == 1131)]
df_inside_cluster.head(20)

name  discount_sum  \
94   Ботинки женские Hanwag Tatra II Bunion Lady GT...        6656.0   
96   Ботинки женские Hanwag Tatra II Bunion Lady GT...        4992.0   
99   Ботинки женские Hanwag Tatra II Bunion Lady GT...        3328.0   
100  Ботинки женские Hanwag Tatra II Bunion Lady GT...        3571.0   
154  Несессер Peak Performance Vertical Toiletry Black         375.0   
166         Шорты женские Krimson Klover Rory 7 Forest        1719.0   
177                 Палатка Alexika Tower 3 Plus Green        6840.0   
207  Куртка женская Ternua Vilma Hood Down Fresh Ocean        4799.0   
308                   Бандана Buff Windproof Xido Grey         758.0   
373  Покрывало Matador Pocket Blanket 3.0 с зеленым...        1035.0   
380  Покрывало Matador Pocket Blanket 3.0 с зеленым...         863.0   
402           Бандана Buff Merino Midweight Solid Bark         464.0   
470      Кроссовки женские Joma Storm Viper коралловый        2200.0   
539        Куртка женская Klattermusen Balder Charcoal        6300.0   
555                    Рюкзак Ortlieb Atrack 25 Petrol        4590.0   
568        Куртка женская Klattermusen Balder Charcoal        4899.0   
654  Ботинки женские Arcteryx Acrux TR GTX Black/Ro...        4815.0   
848                   Бутылка HydraPak Flux 1,5L Серый           0.0   
871  Куртка женская Mountain Hardwear Polartec Doub...        1290.0   
937  Кальсоны женские Icebreaker 260 Tech Leggings ...        1407.0   

     total_sum  prod_unit_price  quarter_1  quarter_2  quarter_3  quarter_4  \
94     26624.0          33280.0          0          0          1          0   
96     28288.0          33280.0          0          0          0          1   
99     29952.0          33280.0          0          0          1          0   
100    29709.0          33280.0          0          0          1          0   
154     7125.0           7500.0          1          0          0          0   
166     6871.0           8590.0          0          1          0          0   
177    27360.0          34200.0          0          1          0          0   
207    27191.0          31990.0          0          0          0          1   
308     3032.0           3790.0          1          0          0          0   
373     2415.0           3450.0          0          0          1          0   
380     2587.0           3450.0          0          0          1          0   
402     2626.0           3090.0          0          1          0          0   
470     6600.0           8800.0          0          1          0          0   
539    25200.0          31500.0          0          0          0          1   
555    26010.0          30600.0          1          0          0          0   
568    26601.0          31500.0          0          0          0          1   
654    27285.0          32100.0          0          1          0          0   
848     3005.0           3005.0          0          0          0          1   
871     7310.0           8600.0          1          0          0          0   
937     7973.0           9380.0          1          0          0          0   

     customer_keys_le  uid_docs_le  clusters  
94               3621         1323      1131  
96                184          560      1131  
99               1663         3476      1131  
100              5198         2358      1131  
154              2769         3202      1131  
166              3105         2438      1131  
177              4474         5914      1131  
207              2041         3947      1131  
308              3011         2991      1131  
373              2799         1131      1131  
380              2620         1351      1131  
402              2539         2670      1131  
470              3532         6434      1131  
539              3975         1103      1131  
555              1082         6199      1131  
568              4817         2475      1131  
654              4929          143      1131  
848              2401         3

In [21]:
#df_nano_tocheck.clusters.info(verbose = True, show_counts = True)

In [22]:
#df_nano_tocheck.clusters.value_counts(dropna=False).head(50)

In [23]:
#df_nano_tocheck.clusters.unique()

In [24]:
df_nano_tocheck.clusters.nunique()

356

In [25]:
df_nano_tocheck.uid_docs_le.nunique()

7290

In [26]:
df_toteach['clusters'] = uid_dc_labels
df_tocheck['clusters'] = uid_dc_labels
#df_tocheck.head(5)

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [28]:
le.fit(df_toteach['clusters'])
clusters_kne = le.transform(df_toteach['clusters'])
df_toteach = df_toteach.copy()
df_toteach['clusters'] = clusters_kne

df_tocheck['clusters'] = clusters_kne

In [29]:
df_inside_cluster = df_tocheck.loc[(df_tocheck['clusters'] == 7)]
#df_inside_cluster.head(20)

In [30]:
#df_tocheck.clusters.value_counts(dropna=False).head(50)

In [31]:
df_tocheck.clusters.nunique()

356

In [32]:
#df_toteach.info(verbose = True, show_counts = True)

In [33]:
data = df_toteach.iloc[:,:-1]
bivouak_data = data.to_numpy()
target = df_toteach.iloc[:,-1:]
bivouak_target = target.to_numpy().reshape(len(df_toteach))  # Нужно, потому что функция потерь принимает одномерный тензор, а тут без reshape получается массив массивов

In [34]:
data.head(5)   # Проверить. что идет по форме в модель в eval mode 

r_value  height  inner_tent_height  depth  rope_diameter  sl_bag_length  \
0      0.0     0.0                0.0    0.0            0.0            0.0   
1      0.0     0.0                0.0    0.0            0.0            0.0   
2      0.0     0.0                0.0    0.0            0.0            0.0   
3      0.0     0.0                0.0    0.0            0.0            0.0   
4      0.0     0.0                0.0    0.0            0.0            0.0   

   sl_bag_height  main_axe_load  volume  real_weight  fill_power_1 000  \
0            0.0            0.0     0.0        0.709                 0   
1            0.0            0.0     0.0        0.709                 0   
2            0.0            0.0     0.0        0.709                 0   
3            0.0            0.0     0.0        0.709                 0   
4            0.0            0.0     0.0        0.709                 0   

   fill_power_550  fill_power_600  fill_power_650  fill_power_700  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   fill_power_750  fill_power_800  fill_power_850  fill_power_900  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   vent_back_0  vent_back_Да  vent_back_Нет  vent_zip_0  \
0            1             0              0           1   
1            1             0              0           1   
2            1             0              0           1   
3            1             0              0           1   
4            1             0              0           1   

   vent_zip_Без вентиляционных молний  vent_zip_На бёдрах  \
0                                   0                   0   
1                                   0                   0   
2                                   0                   0   
3                                   0                   0   
4                                   0                   0   

   vent_zip_На бёдрах и голенях  vent_zip_От бедра до низа брючин  \
0                             0                                 0   
1                             0                                 0   
2                             0                                 0   
3                             0                                 0   
4                             0                                 0   

   vent_zip_От коленей до низа брючин  vent_zip_От талии до низа брючин  \
0                                   0                                 0   
1                                   0                                 0   
2                                   0                                 0   
3                                   0                                 0   
4                                   0                                 0   

   vent_zip_Под рукавами  vent_helmet_0  vent_helmet_Активная вентиляция  \
0                      0              1                                0   
1                      0              1                                0   
2                      0              1                                0   
3                      0              1                                0   
4                      0              1                                0   

   vent_helmet_Пассивная вентиляция  rope_type_0  rope_type_Динамика  \
0                                 0            1                   0   
1                                 0            1                   0  

In [35]:
#data.info(verbose = True, show_counts = True)

In [36]:
bivouak_data.shape

(47818, 478)

In [37]:
bivouak_target.shape

(47818,)

In [38]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(bivouak_data, bivouak_target)

In [40]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)
X_check =  scaler.transform(bivouak_data)    #  !!!!!!! Вот тут!!!! этим же скалером нужно потом новые данные масштабировать????? 

In [41]:
import torch
print('PyTorch version: {}'.format(torch.__version__))
import matplotlib.pyplot as plt
%matplotlib inline
from torch import nn
from IPython.display import clear_output

PyTorch version: 2.2.1


In [42]:
X_train_biv = torch.FloatTensor(X_train)
X_test_biv = torch.FloatTensor(X_test)
X_check_biv = torch.FloatTensor(X_check)

y_train_biv = torch.LongTensor(y_train)
y_test_biv = torch.LongTensor(y_test)

In [43]:
X_train_biv.shape

torch.Size([35863, 478])

In [44]:
y_train_biv.shape

torch.Size([35863])

In [45]:
print(y_train_biv)

tensor([100, 310, 131,  ..., 130, 123, 154])


In [47]:
N_FEATURES = X_train.shape[1]

N_CLASSES = 400
NUM_EPOCH = 500

In [46]:
def create_model(activation, num_features=N_FEATURES, n_out=N_CLASSES):
    model = nn.Sequential()
    model.add_module('lin1', nn.Linear(num_features, 64))
    model.add_module('activation1', activation())
    model.add_module('lin2', nn.Linear(64, 128))
    model.add_module('activation2', activation())
    model.add_module('lin3', nn.Linear(128, 256))
    model.add_module('activation3', activation())
    model.add_module('lin4', nn.Linear(256, 512))
    model.add_module('activation4', activation())
    model.add_module('lin5', nn.Linear(512, 1024))
    model.add_module('activation5', activation())
    model.add_module('lin6', nn.Linear(1024, 512))
    model.add_module('activation6', activation())
    model.add_module('lin7', nn.Linear(512, n_out))

    return model

In [47]:
def train_model(model, X_train_biv, y_train_biv):
    loss_function = nn.CrossEntropyLoss()
    opt = torch.optim.SGD(model.parameters(), lr=0.1)


    loss_history, var_layer_1, var_layer_2, var_layer_3 = [], [], [], []

    for epoch_num in range(NUM_EPOCH):
        opt.zero_grad()

        y_predicted = model(X_train_biv)
        loss = loss_function(y_predicted, y_train_biv)
        reg = 0.005 * (torch.norm(model[0].weight) \
                      + torch.norm(model[2].weight) \
                      + torch.norm(model[4].weight) \
                      + torch.norm(model[6].weight) \
                      + torch.norm(model[8].weight) \
                      + torch.norm(model[10].weight) \
                      + torch.norm(model[12].weight))
        loss += reg
        loss.backward()
        opt.step()

        #loss_history.append(loss.item()) # Always use .item() to store scalars in logs!

       # var_layer_1.append(torch.sum(torch.abs(model[0].weight.grad)).item()/model[0].weight.shape[0])
       # var_layer_2.append(torch.sum(torch.abs(model[2].weight.grad)).item()/model[2].weight.shape[0])
       # var_layer_3.append(torch.sum(torch.abs(model[4].weight.grad)).item()/model[4].weight.shape[0])

    return model
#, loss_history, var_layer_1, var_layer_2, var_layer_3

In [48]:
def create_model_2(activation, num_features=N_FEATURES, n_out=N_CLASSES):
    model = nn.Sequential()
    model.add_module('lin1', nn.Linear(num_features, 1024))
    model.add_module('activation1', activation())
    model.add_module('lin2', nn.Linear(1024, 512))
    model.add_module('activation2', activation())
    model.add_module('lin3', nn.Linear(512, 256))
    model.add_module('activation3', activation())
    model.add_module('lin4', nn.Linear(256, 128))
    model.add_module('activation4', activation())
    model.add_module('lin5', nn.Linear(128, 64))
    model.add_module('activation5', activation())
    model.add_module('lin6', nn.Linear(64, 128))
    model.add_module('activation6', activation())
    model.add_module('lin7', nn.Linear(128, 256))
    model.add_module('activation7', activation())
    model.add_module('lin8', nn.Linear(256, n_out))

    return model

In [49]:
def train_model_2(model, X_train_biv, y_train_biv):
    loss_function = nn.CrossEntropyLoss()
    opt = torch.optim.SGD(model.parameters(), lr=0.1)


    loss_history, var_layer_1, var_layer_2, var_layer_3 = [], [], [], []

    for epoch_num in range(NUM_EPOCH):
        opt.zero_grad()

        y_predicted = model(X_train_biv)
        loss = loss_function(y_predicted, y_train_biv)
        reg = 0.005 * (torch.norm(model[0].weight) \
                      + torch.norm(model[2].weight) \
                      + torch.norm(model[4].weight) \
                      + torch.norm(model[6].weight) \
                      + torch.norm(model[8].weight) \
                      + torch.norm(model[10].weight) \
                      + torch.norm(model[12].weight) \
                      + torch.norm(model[14].weight))
        loss += reg
        loss.backward()
        opt.step()

        #loss_history.append(loss.item()) # Always use .item() to store scalars in logs!

       # var_layer_1.append(torch.sum(torch.abs(model[0].weight.grad)).item()/model[0].weight.shape[0])
       # var_layer_2.append(torch.sum(torch.abs(model[2].weight.grad)).item()/model[2].weight.shape[0])
       # var_layer_3.append(torch.sum(torch.abs(model[4].weight.grad)).item()/model[4].weight.shape[0])

    return model
#, loss_history, var_layer_1, var_layer_2, var_layer_3

In [50]:
model_sigmoid = create_model(nn.Sigmoid)

In [51]:
%%time
out_sigmoid = train_model(model_sigmoid, X_train_biv, y_train_biv)

CPU times: total: 48min 20s
Wall time: 12min 41s


In [52]:
from sklearn.metrics import roc_auc_score, roc_curve, accuracy_score
train_predictions = torch.max(model_sigmoid(X_train_biv).detach().cpu(), dim=1)[1].numpy()
test_predictions = torch.max(model_sigmoid(X_test_biv).detach().cpu(), dim=1)[1].numpy()

print('train accuracy', accuracy_score(train_predictions, y_train_biv))
print('test accuracy', accuracy_score(test_predictions, y_test_biv))

train accuracy 0.051027521400886705
test accuracy 0.05144291091593475


In [53]:
print(train_predictions)

[175 175 175 ... 175 175 175]


In [54]:
with torch.no_grad():
    Z = model_sigmoid(X_check_biv).numpy()
clust = np.argmax(Z, axis=1)

In [55]:
clust.shape

(47818,)

In [56]:
print(clust)

[175 175 175 ... 175 175 175]


In [57]:
#print(out_sigmoid)

In [58]:
df_tocheck = df_tocheck.copy()
df_tocheck['nn_clusters'] = clust.tolist()

In [59]:
df_tocheck.shape

(47818, 481)

In [60]:
df_tocheck.head(5)

name  r_value  height  inner_tent_height  depth  \
0  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   
1  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   
2  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   
3  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   
4  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   

   rope_diameter  sl_bag_length  sl_bag_height  main_axe_load  volume  \
0            0.0            0.0            0.0            0.0     0.0   
1            0.0            0.0            0.0            0.0     0.0   
2            0.0            0.0            0.0            0.0     0.0   
3            0.0            0.0            0.0            0.0     0.0   
4            0.0            0.0            0.0            0.0     0.0   

   real_weight  fill_power_1 000  fill_power_550  fill_power_600  \
0        0.709                 0               0               0   
1        0.709                 0               0               0   
2        0.709                 0               0               0   
3        0.709                 0               0               0   
4        0.709                 0               0               0   

   fill_power_650  fill_power_700  fill_power_750  fill_power_800  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   fill_power_850  fill_power_900  vent_back_0  vent_back_Да  vent_back_Нет  \
0               0               0            1             0              0   
1               0               0            1             0              0   
2               0               0            1             0              0   
3               0               0            1             0              0   
4               0               0            1             0              0   

   vent_zip_0  vent_zip_Без вентиляционных молний  vent_zip_На бёдрах  \
0           1                                   0                   0   
1           1                                   0                   0   
2           1                                   0                   0   
3           1                                   0                   0   
4           1                                   0                   0   

   vent_zip_На бёдрах и голенях  vent_zip_От бедра до низа брючин  \
0                             0                                 0   
1                             0                                 0   
2                             0                                 0   
3                             0                                 0   
4                             0                                 0   

   vent_zip_От коленей до низа брючин  vent_zip_От талии до низа брючин  \
0                                   0                                 0   
1                                   0                                 0   
2                                   0                                 0   
3                                   0                                 0   
4                                   0                                 0   

   vent_zip_Под рукавами  vent_helmet_0  vent_helmet_Активная вентиляция  \
0                      0              1                                0   
1                      0              1                                0   
2                      0              1                                0   
3                      0              1                                0   
4                      0              1                                0   

   vent_helmet_Пассивная вентиляция  rope_type_0  rop

In [62]:
df_inside_cluster = df_tocheck.loc[(df_tocheck['nn_clusters'] == 175)]
df_inside_cluster.head(5)

name  r_value  height  inner_tent_height  depth  \
0  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   
1  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   
2  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   
3  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   
4  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   

   rope_diameter  sl_bag_length  sl_bag_height  main_axe_load  volume  \
0            0.0            0.0            0.0            0.0     0.0   
1            0.0            0.0            0.0            0.0     0.0   
2            0.0            0.0            0.0            0.0     0.0   
3            0.0            0.0            0.0            0.0     0.0   
4            0.0            0.0            0.0            0.0     0.0   

   real_weight  fill_power_1 000  fill_power_550  fill_power_600  \
0        0.709                 0               0               0   
1        0.709                 0               0               0   
2        0.709                 0               0               0   
3        0.709                 0               0               0   
4        0.709                 0               0               0   

   fill_power_650  fill_power_700  fill_power_750  fill_power_800  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   fill_power_850  fill_power_900  vent_back_0  vent_back_Да  vent_back_Нет  \
0               0               0            1             0              0   
1               0               0            1             0              0   
2               0               0            1             0              0   
3               0               0            1             0              0   
4               0               0            1             0              0   

   vent_zip_0  vent_zip_Без вентиляционных молний  vent_zip_На бёдрах  \
0           1                                   0                   0   
1           1                                   0                   0   
2           1                                   0                   0   
3           1                                   0                   0   
4           1                                   0                   0   

   vent_zip_На бёдрах и голенях  vent_zip_От бедра до низа брючин  \
0                             0                                 0   
1                             0                                 0   
2                             0                                 0   
3                             0                                 0   
4                             0                                 0   

   vent_zip_От коленей до низа брючин  vent_zip_От талии до низа брючин  \
0                                   0                                 0   
1                                   0                                 0   
2                                   0                                 0   
3                                   0                                 0   
4                                   0                                 0   

   vent_zip_Под рукавами  vent_helmet_0  vent_helmet_Активная вентиляция  \
0                      0              1                                0   
1                      0              1                                0   
2                      0              1                                0   
3                      0              1                                0   
4                      0              1                                0   

   vent_helmet_Пассивная вентиляция  rope_type_0  rop

In [63]:
df_inside_cluster.shape

(47818, 481)

In [64]:
model_relu = create_model(nn.ReLU)

In [65]:
%%time
out_relu = train_model(model_relu, X_train_biv, y_train_biv)

CPU times: total: 43min 28s
Wall time: 11min 53s


In [66]:
train_predictions_relu = torch.max(model_relu(X_train_biv).detach().cpu(), dim=1)[1].numpy()
test_predictions_relu = torch.max(model_relu(X_test_biv).detach().cpu(), dim=1)[1].numpy()

print('train accuracy', accuracy_score(train_predictions_relu, y_train_biv))
print('test accuracy', accuracy_score(test_predictions_relu, y_test_biv))

train accuracy 0.051027521400886705
test accuracy 0.05144291091593475


In [67]:
print(train_predictions_relu)

[175 175 175 ... 175 175 175]


In [68]:
with torch.no_grad():
    Zr = model_relu(X_check_biv).numpy()
clust_relu = np.argmax(Zr, axis=1)

In [69]:
clust_relu.shape

(47818,)

In [70]:
print(clust_relu)

[175 175 175 ... 175 175 175]


In [71]:
df_tocheck = df_tocheck.copy()
df_tocheck['nn_clusters_relu'] = clust_relu.tolist()

In [72]:
df_tocheck.shape

(47818, 482)

In [73]:
df_tocheck.head(5)

name  r_value  height  inner_tent_height  depth  \
0  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   
1  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   
2  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   
3  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   
4  Тент ENO ProFly XL Sil Lichen      0.0     0.0                0.0    0.0   

   rope_diameter  sl_bag_length  sl_bag_height  main_axe_load  volume  \
0            0.0            0.0            0.0            0.0     0.0   
1            0.0            0.0            0.0            0.0     0.0   
2            0.0            0.0            0.0            0.0     0.0   
3            0.0            0.0            0.0            0.0     0.0   
4            0.0            0.0            0.0            0.0     0.0   

   real_weight  fill_power_1 000  fill_power_550  fill_power_600  \
0        0.709                 0               0               0   
1        0.709                 0               0               0   
2        0.709                 0               0               0   
3        0.709                 0               0               0   
4        0.709                 0               0               0   

   fill_power_650  fill_power_700  fill_power_750  fill_power_800  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   fill_power_850  fill_power_900  vent_back_0  vent_back_Да  vent_back_Нет  \
0               0               0            1             0              0   
1               0               0            1             0              0   
2               0               0            1             0              0   
3               0               0            1             0              0   
4               0               0            1             0              0   

   vent_zip_0  vent_zip_Без вентиляционных молний  vent_zip_На бёдрах  \
0           1                                   0                   0   
1           1                                   0                   0   
2           1                                   0                   0   
3           1                                   0                   0   
4           1                                   0                   0   

   vent_zip_На бёдрах и голенях  vent_zip_От бедра до низа брючин  \
0                             0                                 0   
1                             0                                 0   
2                             0                                 0   
3                             0                                 0   
4                             0                                 0   

   vent_zip_От коленей до низа брючин  vent_zip_От талии до низа брючин  \
0                                   0                                 0   
1                                   0                                 0   
2                                   0                                 0   
3                                   0                                 0   
4                                   0                                 0   

   vent_zip_Под рукавами  vent_helmet_0  vent_helmet_Активная вентиляция  \
0                      0              1                                0   
1                      0              1                                0   
2                      0              1                                0   
3                      0              1                                0   
4                      0              1                                0   

   vent_helmet_Пассивная вентиляция  rope_type_0  rop

In [74]:
df_inside_cluster = df_tocheck.loc[(df_tocheck['nn_clusters_relu'] == 175)]
df_inside_cluster.head(20)

name  r_value  height  \
0                       Тент ENO ProFly XL Sil Lichen      0.0     0.0   
1                       Тент ENO ProFly XL Sil Lichen      0.0     0.0   
2                       Тент ENO ProFly XL Sil Lichen      0.0     0.0   
3                       Тент ENO ProFly XL Sil Lichen      0.0     0.0   
4                       Тент ENO ProFly XL Sil Lichen      0.0     0.0   
5                       Тент ENO ProFly XL Sil Lichen      0.0     0.0   
6                       Тент ENO ProFly XL Sil Lichen      0.0     0.0   
7    Горнолыжный шлем Alpina Grand Charcoal/Neon Matt      0.0     0.0   
8   Брюки женские Ternua Rotar Warm Dark Teal/Fres...      0.0     0.0   
9                  Кроссовки мужские Joma Shock серый      0.0     0.0   
10           Бандана Buff Merino Lightweight Den Bark      0.0     0.0   
11           Бандана Buff Merino Lightweight Den Bark      0.0     0.0   
12           Бандана Buff Merino Lightweight Den Bark      0.0     0.0   
13           Бандана Buff Merino Lightweight Den Bark      0.0     0.0   
14           Бандана Buff Merino Lightweight Den Bark      0.0     0.0   
15                 Шапка Fjallraven Classic Knit Grey      0.0     0.0   
16  Футболка женская Krimson Klover Sara L/S Sunbu...      0.0     0.0   
17  Футболка женская Krimson Klover Sara L/S Sunbu...      0.0     0.0   
18  Футболка женская Krimson Klover Sara L/S Sunbu...      0.0     0.0   
19  Футболка женская Krimson Klover Sara L/S Sunbu...      0.0     0.0   

    inner_tent_height  depth  rope_diameter  sl_bag_length  sl_bag_height  \
0                 0.0    0.0            0.0            0.0            0.0   
1                 0.0    0.0            0.0            0.0            0.0   
2                 0.0    0.0            0.0            0.0            0.0   
3                 0.0    0.0            0.0            0.0            0.0   
4                 0.0    0.0            0.0            0.0            0.0   
5                 0.0    0.0            0.0            0.0            0.0   
6                 0.0    0.0            0.0            0.0            0.0   
7                 0.0    0.0            0.0            0.0            0.0   
8                 0.0    0.0            0.0            0.0            0.0   
9                 0.0    0.0            0.0            0.0            0.0   
10                0.0    0.0            0.0            0.0            0.0   
11                0.0    0.0            0.0            0.0            0.0   
12                0.0    0.0            0.0            0.0            0.0   
13                0.0    0.0            0.0            0.0            0.0   
14                0.0    0.0            0.0            0.0            0.0   
15                0.0    0.0            0.0            0.0            0.0   
16                0.0    0.0            0.0            0.0            0.0   
17                0.0    0.0            0.0            0.0            0.0   
18                0.0    0.0            0.0            0.0            0.0   
19                0.0    0.0            0.0            0.0            0.0   

    main_axe_load  volume  real_weight  fill_power_1 000  fill_power_550  \
0             0.0     0.0        0.709                 0               0   
1             0.0     0.0        0.709                 0               0   
2             0.0     0.0        0.709                 0               0   
3             0.0     0.0        0.709                 0               0   
4             0.0     0.0        0.709                 0               0   
5             0.0     0.0        0.709                 0               0   
6             0.0     0.0        0.709                 0               0   
7             0.0     0.0        0.000                 0               0   
8             0.0     0.0        0.455                 0               0   
9             0.0     0.0        0.300                 0               0   
10            0.0     0.0        0.000  

In [75]:
df_inside_cluster.shape

(47818, 482)

In [76]:
model_sigmoid_2 = create_model_2(nn.Sigmoid)

In [77]:
%%time
out_sigmoid_2 = train_model_2(model_sigmoid_2, X_train_biv, y_train_biv)

CPU times: total: 39min 23s
Wall time: 11min 5s


In [78]:
from sklearn.metrics import roc_auc_score, roc_curve, accuracy_score
train_predictions_2 = torch.max(model_sigmoid_2(X_train_biv).detach().cpu(), dim=1)[1].numpy()
test_predictions_2 = torch.max(model_sigmoid_2(X_test_biv).detach().cpu(), dim=1)[1].numpy()

print('train accuracy', accuracy_score(train_predictions_2, y_train_biv))
print('test accuracy', accuracy_score(test_predictions_2, y_test_biv))

train accuracy 0.051027521400886705
test accuracy 0.05144291091593475


In [79]:
print(train_predictions_2)

[175 175 175 ... 175 175 175]


In [80]:
model_relu_2 = create_model_2(nn.ReLU)

In [81]:
%%time
out_relu_2 = train_model_2(model_relu_2, X_train_biv, y_train_biv)

CPU times: total: 36min 51s
Wall time: 10min 34s


In [82]:
train_predictions_relu_2 = torch.max(model_relu_2(X_train_biv).detach().cpu(), dim=1)[1].numpy()
test_predictions_relu_2 = torch.max(model_relu_2(X_test_biv).detach().cpu(), dim=1)[1].numpy()

print('train accuracy', accuracy_score(train_predictions_relu_2, y_train_biv))
print('test accuracy', accuracy_score(test_predictions_relu_2, y_test_biv))

train accuracy 0.051027521400886705
test accuracy 0.05144291091593475


In [83]:
print(train_predictions_relu_2)

[175 175 175 ... 175 175 175]


In [46]:
def create_model_3(activation, num_features=N_FEATURES, n_out=N_CLASSES):
    model = nn.Sequential()
    model.add_module('lin1', nn.Linear(num_features, 256))
    model.add_module('activation1', activation())
    model.add_module('lin2', nn.Linear(256, 512))
    model.add_module('activation2', activation())
    model.add_module('lin3', nn.Linear(512, 1024))
    model.add_module('activation3', activation())
    model.add_module('lin4', nn.Linear(1024, 512))
    model.add_module('activation4', activation())
    model.add_module('lin5', nn.Linear(512, 256))
    model.add_module('activation5', activation())
    model.add_module('lin6', nn.Linear(256, n_out))

    return model

In [47]:
def train_model_3(model, X_train_biv, y_train_biv):
    loss_function = nn.CrossEntropyLoss()
    opt = torch.optim.SGD(model.parameters(), lr=0.1)


    loss_history, var_layer_1, var_layer_2, var_layer_3 = [], [], [], []

    for epoch_num in range(NUM_EPOCH):
        opt.zero_grad()

        y_predicted = model(X_train_biv)
        loss = loss_function(y_predicted, y_train_biv)
        reg = 0.005 * (torch.norm(model[0].weight) \
                      + torch.norm(model[2].weight) \
                      + torch.norm(model[4].weight) \
                      + torch.norm(model[6].weight) \
                      + torch.norm(model[8].weight) \
                      + torch.norm(model[10].weight))
        loss += reg
        loss.backward()
        opt.step()

        #loss_history.append(loss.item()) # Always use .item() to store scalars in logs!

       # var_layer_1.append(torch.sum(torch.abs(model[0].weight.grad)).item()/model[0].weight.shape[0])
       # var_layer_2.append(torch.sum(torch.abs(model[2].weight.grad)).item()/model[2].weight.shape[0])
       # var_layer_3.append(torch.sum(torch.abs(model[4].weight.grad)).item()/model[4].weight.shape[0])

    return model
#, loss_history, var_layer_1, var_layer_2, var_layer_3

In [48]:
model_relu_3 = create_model_3(nn.ReLU)

In [49]:
%%time
out_relu_3 = train_model_3(model_relu_3, X_train_biv, y_train_biv)

CPU times: total: 44min 22s
Wall time: 12min 42s


In [51]:
from sklearn.metrics import roc_auc_score, roc_curve, accuracy_score
train_predictions_relu_3 = torch.max(model_relu_3(X_train_biv).detach().cpu(), dim=1)[1].numpy()
test_predictions_relu_3 = torch.max(model_relu_3(X_test_biv).detach().cpu(), dim=1)[1].numpy()

print('train accuracy', accuracy_score(train_predictions_relu_3, y_train_biv))
print('test accuracy', accuracy_score(test_predictions_relu_3, y_test_biv))

train accuracy 0.0431363801132086
test accuracy 0.04123797574236721


In [52]:
print(train_predictions_relu_3)

[312 312 312 ... 312  79  79]


In [48]:
def create_model_4(activation, num_features=N_FEATURES, n_out=N_CLASSES):
    model = nn.Sequential()
    model.add_module('lin1', nn.Linear(num_features, 1024))  
    model.add_module('lin2', nn.Linear(1024, 512))   
    model.add_module('lin3', nn.Linear(512, 256))    
    model.add_module('lin4', nn.Linear(256, 128))
    model.add_module('activation1', activation())
    model.add_module('lin5', nn.Linear(128, 64))    
    model.add_module('lin6', nn.Linear(64, 128))   
    model.add_module('lin7', nn.Linear(128, 256))
    model.add_module('activation2', activation())
    model.add_module('lin8', nn.Linear(256, n_out))

    return model

In [50]:
def train_model_4(model, X_train_biv, y_train_biv):
    loss_function = nn.CrossEntropyLoss()
    opt = torch.optim.SGD(model.parameters(), lr=0.1)


   

    for epoch_num in range(NUM_EPOCH):
        opt.zero_grad()

        y_predicted = model(X_train_biv)
        loss = loss_function(y_predicted, y_train_biv)
        
        loss.backward()
        opt.step()
    return model


In [51]:
model_relu_4 = create_model_4(nn.ReLU)

In [52]:
%%time
out_relu_4 = train_model_4(model_relu_4, X_train_biv, y_train_biv)

CPU times: total: 43min 6s
Wall time: 9min 42s


In [53]:
from sklearn.metrics import roc_auc_score, roc_curve, accuracy_score
train_predictions_relu_4 = torch.max(model_relu_4(X_train_biv).detach().cpu(), dim=1)[1].numpy()
test_predictions_relu_4 = torch.max(model_relu_4(X_test_biv).detach().cpu(), dim=1)[1].numpy()

print('train accuracy', accuracy_score(train_predictions_relu_4, y_train_biv))
print('test accuracy', accuracy_score(test_predictions_relu_4, y_test_biv))

train accuracy 0.05735716476591473
test accuracy 0.05872020075282309


In [55]:
print(train_predictions_relu_4)

[ 15  15 290 ... 290 312  15]


In [56]:
with torch.no_grad():
    Zr = model_relu_4(X_check_biv).numpy()
clust_relu4 = np.argmax(Zr, axis=1)

In [57]:
clust_relu4.shape

(47818,)

In [58]:
print(clust_relu4)

[ 79  79  79 ... 312 312 312]


In [59]:
df_tocheck4 = df_tocheck.copy()
df_tocheck4['nn_clusters_relu'] = clust_relu4.tolist()

In [60]:
df_tocheck4.nn_clusters_relu.value_counts()

312    16778
79     10998
15      9338
290     7522
1       2825
58       318
116       39
Name: nn_clusters_relu, dtype: int64

In [80]:
df_pr = pd.read_csv('corr_sales_biv_preprocess_24_test.csv', encoding='cp1251', sep=',', low_memory=False)
pd.set_option('display.max_columns', None)
df_pr.head(5)
df_pr.drop('Unnamed: 0', axis= 1 , inplace= True )

In [81]:
df2_full_pr = df_pr.iloc[:,[1,16,27,28,32,33,34,35,40,43,44]]
df2_data_pr = df_pr.iloc[:,[16,27,28,32,33,34,35,40,43,44]]
df2_data_pr.head(5)

r_value  height  inner_tent_height  depth  rope_diameter  sl_bag_length  \
0      0.0     0.0                0.0    0.0            0.0            0.0   
1      0.0     0.0                0.0    0.0            0.0            0.0   
2      0.0     0.0                0.0    0.0            0.0            0.0   
3      0.0     0.0                0.0    0.0            0.0            0.0   
4      0.0     0.0                0.0    0.0            0.0            0.0   

   sl_bag_height  main_axe_load  volume  real_weight  
0            0.0            0.0     0.0        0.009  
1            0.0            0.0     0.0        0.009  
2            0.0            0.0     1.0        0.070  
3            0.0            0.0     1.0        0.070  
4            0.0            0.0     1.0        0.070

In [82]:
df3_pr = df_pr.iloc[:,55:529]
df3_pr.head(5)

fill_power_1 000  fill_power_550  fill_power_600  fill_power_650  \
0                 0               0               0               0   
1                 0               0               0               0   
2                 0               0               0               0   
3                 0               0               0               0   
4                 0               0               0               0   

   fill_power_700  fill_power_750  fill_power_800  fill_power_850  \
0               0               0               0               0   
1               0               0               0               0   
2               0               0               0               0   
3               0               0               0               0   
4               0               0               0               0   

   fill_power_900  vent_back_0  vent_back_Да  vent_back_Нет  vent_zip_0  \
0               0            1             0              0           1   
1               0            1             0              0           1   
2               0            1             0              0           1   
3               0            1             0              0           1   
4               0            1             0              0           1   

   vent_zip_Без вентиляционных молний  vent_zip_На бёдрах  \
0                                   0                   0   
1                                   0                   0   
2                                   0                   0   
3                                   0                   0   
4                                   0                   0   

   vent_zip_На бёдрах и голенях  vent_zip_От бедра до низа брючин  \
0                             0                                 0   
1                             0                                 0   
2                             0                                 0   
3                             0                                 0   
4                             0                                 0   

   vent_zip_От коленей до низа брючин  vent_zip_От талии до низа брючин  \
0                                   0                                 0   
1                                   0                                 0   
2                                   0                                 0   
3                                   0                                 0   
4                                   0                                 0   

   vent_zip_Под рукавами  vent_helmet_0  vent_helmet_Активная вентиляция  \
0                      0              1                                0   
1                      0              1                                0   
2                      0              1                                0   
3                      0              1                                0   
4                      0              1                                0   

   vent_helmet_Пассивная вентиляция  rope_type_0  rope_type_Динамика  \
0                                 0            1                   0   
1                                 0            1                   0   
2                                 0            1                   0   
3                                 0            1                   0   
4                                 0            1                   0   

   rope_type_Паракорд  rope_type_Репшнур  rope_type_Статика  rope_type_Стропа  \
0                   0                  0                  0                 0   
1                   0                  0                  0                 0   
2                   0                  0                  0                 0   
3                   0                  0                  0                 0   
4                   0                  0                  0                 0   

   sling_type_0  sling_type_Оттяжки с карабинами  sling_type_Петли и оттяжки  \
0             1     

In [86]:
df_toteach_pr = pd.concat([df2_data_pr,df3_pr], axis=1)
df_tocheck_pr = pd.concat([df2_full_pr,df3_pr], axis=1)

In [ ]:
#uid_dc_labels = clf.predict(X)

In [ ]:
#df_toteach['clusters'] = uid_dc_labels

In [ ]:
#from sklearn.preprocessing import LabelEncoder
#le = LabelEncoder()

In [ ]:
#le.fit(df_toteach['clusters'])
#clusters_kne = le.transform(df_toteach['clusters'])
#df_toteach = df_toteach.copy()
#df_toteach['clusters'] = clusters_kne

In [ ]:
#data = df_toteach.iloc[:,:-1]
#bivouak_data = data.to_numpy()

In [87]:
bivouak_data_hebd = df_toteach_pr.to_numpy()

In [89]:
bivouak_data_hebd.shape

(7854, 484)

In [90]:
# тут оч большой вопрос, используем ли тот же scalerдля масштабирования????

In [91]:
X_hebd =  scaler.transform(bivouak_data_hebd)

In [92]:
X_hebd_biv = torch.FloatTensor(X_hebd)

In [96]:
with torch.no_grad():
    Zhebd = model_relu(X_hebd_biv).numpy()
clust_hebd = np.argmax(Zhebd, axis=1)

In [97]:
clust_hebd.shape

(7854,)

In [98]:
print(clust_hebd)

[312 312 312 ... 312 312 312]


In [ ]:
#df_pr

In [ ]:
#df_tocheck = df_tocheck.copy()
#df_tocheck['nn_clusters_relu'] = clust_hebd.tolist()

In [ ]:
#df_tocheck.shape

In [ ]:
#df_tocheck.head(5)

In [99]:
df_outcluster_hebd = df_pr.iloc[:,0:6]
#df_outcluster.head(5)

In [100]:
df_outcluster_hebd['nn_clusters_relu'] = clust_hebd.tolist()

In [101]:
df_outcluster_hebd.head(5)

uid                             name  \
0  00fae3ac-1bab-11e7-80c7-901b0e95a2a8             Ложка-Вилка MSR Blue   
1  00fae3ac-1bab-11e7-80c7-901b0e95a2a8             Ложка-Вилка MSR Blue   
2  05e85429-0f4c-11ee-85da-b42e99c9b482  Фляга Source Nomadic 1,0 л Blue   
3  05e85429-0f4c-11ee-85da-b42e99c9b482  Фляга Source Nomadic 1,0 л Blue   
4  05e85429-0f4c-11ee-85da-b42e99c9b482  Фляга Source Nomadic 1,0 л Blue   

         category1_name            category2_name category3_name  \
0  Туристическая посуда             Вилки и ложки            NaN   
1  Туристическая посуда             Вилки и ложки            NaN   
2  Туристическая посуда  Фляги, канистры, ёмкости            NaN   
3  Туристическая посуда  Фляги, канистры, ёмкости            NaN   
4  Туристическая посуда  Фляги, канистры, ёмкости            NaN   

  category4_name  nn_clusters_relu  
0            NaN               312  
1            NaN               312  
2            NaN               312  
3            NaN               312  
4            NaN               312

In [102]:
df_outcluster_hebd.to_csv('biv_clustered.csv', encoding='cp1251', sep=',')

Альтернативный трек: запишем выход из KNN

In [61]:
df_pr = pd.read_csv('corr_sales_biv_preprocess_24_test.csv', encoding='cp1251', sep=',', low_memory=False)
pd.set_option('display.max_columns', None)
df_pr.head(5)
df_pr.drop('Unnamed: 0', axis= 1 , inplace= True )

In [64]:
df_outcluster_knn = df.iloc[:,0:6]

In [65]:
df_outcluster_knn['clusters'] = clusters_kne

In [66]:
df_outcluster_knn.head(5)

uid                           name  \
0  00e7d508-7577-11e9-80ca-901b0e95a2a8  Тент ENO ProFly XL Sil Lichen   
1  00e7d508-7577-11e9-80ca-901b0e95a2a8  Тент ENO ProFly XL Sil Lichen   
2  00e7d508-7577-11e9-80ca-901b0e95a2a8  Тент ENO ProFly XL Sil Lichen   
3  00e7d508-7577-11e9-80ca-901b0e95a2a8  Тент ENO ProFly XL Sil Lichen   
4  00e7d508-7577-11e9-80ca-901b0e95a2a8  Тент ENO ProFly XL Sil Lichen   

  category1_name                   category2_name category3_name  \
0        Палатки  Тенты и противомоскитные пологи            NaN   
1        Палатки  Тенты и противомоскитные пологи            NaN   
2        Палатки  Тенты и противомоскитные пологи            NaN   
3        Палатки  Тенты и противомоскитные пологи            NaN   
4        Палатки  Тенты и противомоскитные пологи            NaN   

  category4_name  clusters  
0            NaN        95  
1            NaN        95  
2            NaN        95  
3            NaN        95  
4            NaN        71

In [67]:
df_outcluster_knn.to_csv('biv_clustered_knn.csv', encoding='cp1251', sep=',')